import { useState, useRef } from "react";
import * as XLSX from "xlsx";
import Modal from "./Modal";
import { useToast } from "../../contexts/ToastContext";
import { useLookups } from "../../contexts/LookupsContext";
import { parseFile, type ParseResult } from "../../lib/import/parse";
import { validateRows, type ValidatedRow } from "../../lib/import/validate";
import { commitImport } from "../../lib/import/commit";
import type { ImportSpec } from "../../types/config";

type Props = {
  open: boolean;
  onClose: () => void;
  onImported: () => void;
  spec: ImportSpec;
};

export default function ImportModal({ open, onClose, onImported, spec }: Props) {
  const { success, error } = useToast();
  const lookups = useLookups();
  const inputRef = useRef<HTMLInputElement>(null);

  const [fileName, setFileName] = useState<string>("");
  const [parsed, setParsed] = useState<ParseResult | null>(null);
  const [validated, setValidated] = useState<ValidatedRow[] | null>(null);
  const [busy, setBusy] = useState(false);
  const [drag, setDrag] = useState(false);

  function reset() {
    setFileName("");
    setParsed(null);
    setValidated(null);
    setBusy(false);
    setDrag(false);
    if (inputRef.current) inputRef.current.value = "";
  }

  function close() {
    reset();
    onClose();
  }

  async function handleFile(file: File) {
    if (!file) return;
    setBusy(true);
    try {
      const p = await parseFile(file, spec.columns);
      const v = validateRows(p.rows, p.mappedHeaders, spec.columns, lookups);
      setFileName(file.name);
      setParsed(p);
      setValidated(v);
    } catch (err) {
      error(err instanceof Error ? err.message : "Failed to parse file");
      reset();
    } finally {
      setBusy(false);
    }
  }

  async function doImport() {
    if (!validated) return;
    setBusy(true);
    try {
      const result = await commitImport(spec.table, validated, fileName);
      if (result.imported === 0) {
        error("No valid rows to import.");
      } else {
        success(
          `Imported ${result.imported} row${result.imported === 1 ? "" : "s"}` +
            (result.skipped ? ` · skipped ${result.skipped}` : "")
        );
        onImported();
        close();
      }
    } catch (err) {
      error(err instanceof Error ? err.message : "Import failed");
    } finally {
      setBusy(false);
    }
  }

  function downloadTemplate() {
    const headers = spec.columns.map((c) => c.label);
    const sample = spec.columns.map((c) => spec.sample[c.label] ?? "");
    const ws = XLSX.utils.aoa_to_sheet([headers, sample]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, `${spec.table}_import_template.xlsx`);
    success("Template downloaded");
  }

  const missingRequired = parsed
    ? spec.columns.filter((c) => c.required && !parsed.mappedHeaders[c.key])
    : [];

  const totalValid = validated ? validated.filter((v) => !v.errors.length).length : 0;
  const totalInvalid = validated ? validated.length - totalValid : 0;
  const canImport = validated && !missingRequired.length && totalValid > 0;

  /* ---------- Stage 1: no file yet ---------- */
  if (!parsed) {
    return (
      <Modal
        open={open}
        onClose={close}
        title={`Import ${spec.title}`}
        footer={
          <>
            <button className="btn btn-ghost" onClick={downloadTemplate}>
              Download Template
            </button>
            <button className="btn btn-ghost" onClick={close}>
              Cancel
            </button>
          </>
        }
      >
        <div
          style={{
            background: "#eff6ff",
            border: "1px solid #bfdbfe",
            borderRadius: 10,
            padding: "10px 14px",
            fontSize: 11.5,
            color: "#1e40af",
          }}
        >
          Upload an Excel (<strong>.xlsx</strong>, <strong>.xls</strong>) or CSV file.
          Column headers are auto-detected. <strong>External IDs are always generated by
          the system</strong> — don't include them in your file.
        </div>

        <div
          className="drop-zone"
          onClick={() => inputRef.current?.click()}
          onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
          onDragLeave={() => setDrag(false)}
          onDrop={(e) => {
            e.preventDefault();
            setDrag(false);
            const f = e.dataTransfer.files[0];
            if (f) handleFile(f);
          }}
          style={{
            border: `2px dashed ${drag ? "#4f46e5" : "#e6ebf2"}`,
            background: drag ? "#eef2ff" : "#fafbfd",
            borderRadius: 12,
            padding: "38px 20px",
            textAlign: "center",
            cursor: "pointer",
          }}
        >
          <svg
            width="44"
            height="44"
            viewBox="0 0 24 24"
            fill="none"
            stroke={drag ? "#4f46e5" : "#94a3b8"}
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeLinejoin="round"
            style={{ marginBottom: 12 }}
          >
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="17 8 12 3 7 8" />
            <line x1="12" y1="3" x2="12" y2="15" />
          </svg>
          <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 4 }}>
            Drop your file here, or click to browse
          </div>
          <div style={{ fontSize: 11.5, color: "#64748b" }}>
            Supports .xlsx · .xls · .csv
          </div>
          <input
            ref={inputRef}
            type="file"
            accept=".xlsx,.xls,.csv"
            style={{ display: "none" }}
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) handleFile(f);
            }}
          />
        </div>

        {busy && (
          <div style={{ textAlign: "center", fontSize: 12.5, color: "#64748b" }}>
            Parsing file…
          </div>
        )}
      </Modal>
    );
  }

  /* ---------- Stage 2: preview ---------- */
  const preview = validated!.slice(0, 50);

  return (
    <Modal
      open={open}
      onClose={close}
      title={`Import ${spec.title} — Preview`}
      wide
      footer={
        <>
          <button className="btn btn-ghost" onClick={reset} disabled={busy}>
            ← Upload different file
          </button>
          <button className="btn btn-ghost" onClick={close} disabled={busy}>
            Cancel
          </button>
          <button className="btn btn-primary" onClick={doImport} disabled={!canImport || busy}>
            {busy ? "Importing…" : `Import ${totalValid} row${totalValid === 1 ? "" : "s"}`}
          </button>
        </>
      }
    >
      <div
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: 8,
          padding: "7px 12px",
          background: "#eef2ff",
          border: "1px solid #c7d2fe",
          borderRadius: 8,
          fontSize: 12,
          color: "#4f46e5",
          fontWeight: 600,
        }}
      >
        {fileName} · {validated!.length} row{validated!.length === 1 ? "" : "s"}
      </div>

      {/* Column mapping */}
      <div className="section-title">Column Mapping</div>
      <div style={{ display: "grid", gap: 6 }}>
        {spec.columns.map((col) => {
          const header = parsed.mappedHeaders[col.key];
          return (
            <div
              key={col.key}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                padding: "7px 11px",
                background: "#fafbfd",
                border: "1px solid #e6ebf2",
                borderRadius: 8,
                fontSize: 12,
              }}
            >
              <span style={{ fontWeight: 600, minWidth: 150 }}>
                {col.label}
                {col.required && <span style={{ color: "#ef4444" }}> *</span>}
              </span>
              <span style={{ color: "#94a3b8" }}>←</span>
              <span style={{ color: "#64748b", fontStyle: "italic" }}>
                {header ?? "not found"}
              </span>
              <span
                style={{
                  marginLeft: "auto",
                  fontWeight: 700,
                  color: header ? "#10b981" : "#ef4444",
                }}
              >
                {header ? "✓" : "missing"}
              </span>
            </div>
          );
        })}
      </div>

      {missingRequired.length > 0 && (
        <div
          style={{
            background: "#fffbeb",
            border: "1px solid #fde68a",
            color: "#92400e",
            padding: "10px 14px",
            borderRadius: 10,
            fontSize: 11.5,
          }}
        >
          Required column(s) missing: <strong>{missingRequired.map((c) => c.label).join(", ")}</strong>.
          Update your file headers and re-upload.
        </div>
      )}

      {/* Summary */}
      <div className="section-title">Validation Summary</div>
      <div style={{ display: "flex", gap: 18, flexWrap: "wrap", fontSize: 12.5 }}>
        <div>
          <span style={{ color: "#64748b" }}>Valid rows: </span>
          <strong style={{ color: "#10b981" }}>{totalValid}</strong>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>Errors: </span>
          <strong style={{ color: "#ef4444" }}>{totalInvalid}</strong>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>Total parsed: </span>
          <strong>{validated!.length}</strong>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>Previewing: </span>
          <strong>{preview.length}</strong>
        </div>
      </div>

      {/* Preview table */}
      <div className="section-title">Preview (first {preview.length} rows)</div>
      <div
        style={{
          maxHeight: 320,
          overflow: "auto",
          border: "1px solid #e6ebf2",
          borderRadius: 10,
        }}
      >
        <table style={{ fontSize: 11.5 }}>
          <thead>
            <tr>
              {spec.columns.map((c) => (
                <th key={c.key}>{c.label}</th>
              ))}
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {preview.map((r) => (
              <tr
                key={r.index}
                style={r.errors.length ? { background: "#fef2f2" } : undefined}
              >
                {spec.columns.map((c) => (
                  <td
                    key={c.key}
                    style={r.errors.length ? { color: "#b91c1c" } : undefined}
                  >
                    {String(r.resolved[c.key] ?? "")}
                  </td>
                ))}
                <td>
                  {r.errors.length ? (
                    <span className="badge badge-danger" title={r.errors.join("; ")}>
                      {r.errors.length} error{r.errors.length > 1 ? "s" : ""}
                    </span>
                  ) : (
                    <span className="badge badge-success">OK</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Modal>
  );
}